/* pins.js — リサーチマップのピンデータ
 * cat: person | company | product | city | history
 * source: 関連リサーチページへの相対パス
 */
const PINS = [
  /* ============ NO.2 LEGENDS（人物・出身地） ============ */
  { cat:'person', name:'Tim Cook',           lat:30.5532, lng:-87.7080, place:'Robertsdale, Alabama, USA',  source:'../no2-legends/tim-cook.html',
    detail:'Apple CEO（2011〜）の出身地。Auburn University卒業後IBMで12年・Compaqで半年を経て1998年にAppleに入社、SteveJobsの下でCOOへ。' },
  { cat:'person', name:'Charlie Munger',     lat:41.2565, lng:-95.9345, place:'Omaha, Nebraska, USA',        source:'../no2-legends/charlie-munger.html',
    detail:'Berkshire Hathaway副会長（1978〜2023）。Buffettの相棒として64年間。生まれ・少年期もOmaha。' },
  { cat:'person', name:'Sundar Pichai',      lat:9.9252,  lng:78.1198,  place:'Madurai, Tamil Nadu, India',  source:'../no2-legends/sundar-pichai.html',
    detail:'Google CEO（2015〜）／Alphabet CEO。生まれはインド南部Madurai。IIT KharagpurからStanford・Whartonを経てGoogleへ。' },
  { cat:'person', name:'Steve Ballmer',      lat:42.3314, lng:-83.0458, place:'Detroit, Michigan, USA',      source:'../no2-legends/steve-ballmer.html',
    detail:'元Microsoft CEO。Harvard寮の隣人だったBill Gatesに4%の自社株で引き抜かれた。' },
  { cat:'person', name:'Jony Ive',           lat:51.6308, lng:-0.0177,  place:'Chingford, London, UK',       source:'../no2-legends/jony-ive.html',
    detail:'元Apple最高デザイン責任者→OpenAIへ。iMac〜iPhoneまでJobsの「触れる形」を設計した美学のNo.2。' },
  { cat:'person', name:'Sheryl Sandberg',    lat:38.9072, lng:-77.0369, place:'Washington D.C., USA',        source:'../no2-legends/sheryl-sandberg.html',
    detail:'元Meta（Facebook）COO。生まれはDC、Miamiで育つ。Harvardで修士。Zuckerbergの隣でFacebookを広告事業化。' },
  { cat:'person', name:'Greg Brockman',      lat:47.7775, lng:-97.1131, place:'North Dakota, USA',           source:'../no2-legends/greg-brockman.html',
    detail:'OpenAI President／共同創業者。北部の小さな町出身、Harvard中退→MIT中退→StripeでCTO→2015年OpenAI共同創業。' },
  { cat:'person', name:'Eric Schmidt',       lat:38.8823, lng:-77.1711, place:'Falls Church, Virginia, USA', source:'../no2-legends/eric-schmidt.html',
    detail:'元Google CEO（2001〜2011）。Larry/Sergeyの「adult supervision」として10年。' },
  { cat:'person', name:'John Collison',      lat:52.6638, lng:-8.6267,  place:'Limerick, Ireland',           source:'../no2-legends/john-collison.html',
    detail:'Stripe共同創業者・President。17歳でAuctomaticを売却、19歳でHarvard中退、26歳で世界最年少自力ビリオネア。' },
  { cat:'person', name:'Mira Murati',        lat:40.4686, lng:19.4894,  place:'Vlorë, Albania',              source:'../no2-legends/mira-murati.html',
    detail:'元OpenAI CTO（〜2024）。アルバニア生まれ、16歳でカナダへ。ChatGPT・GPT-4・Soraを束ねた技術No.2。' },
  { cat:'person', name:'David Sacks',        lat:-33.9249, lng:18.4241, place:'Cape Town, South Africa',     source:'../no2-legends/david-sacks.html',
    detail:'元PayPal COO（〜2002）。南アで生まれ、5歳で渡米。StanfordでThielと出会いPayPalマフィアの一人に。Trump政権でAI/Crypto Czar。' },
  { cat:'person', name:'小泉文明',           lat:35.6635, lng:138.5685, place:'山梨県, Japan',              source:'../no2-legends/fumiaki-koizumi.html',
    detail:'元メルカリ会長／COO→社長→会長と動きながら2019年に自発的に社長を山田進太郎に返した「逆継承型」No.2。' },
  { cat:'person', name:'前田ヒロ',           lat:35.6762, lng:139.6503, place:'東京, Japan',                source:'../no2-legends/hiro-maeda.html',
    detail:'ALL STAR SAAS FUND代表。22歳で佐々木大輔と意気投合、Open Network Lab→BEENEXTを共に作り2019年巣立ち。' },
  { cat:'person', name:'東後 澄人',          lat:35.6762, lng:139.6503, place:'東京, Japan',                source:'../no2-legends/togo-sumito.html',
    detail:'元freee COO/CFO/CPO。McKinsey→Google→freeeで11年半、SaaS史上初のグローバルIPO主導。退任後はAstroXで宇宙へ。' },
  { cat:'person', name:'高宮 慎一',          lat:35.6762, lng:139.6503, place:'東京, Japan',                source:'../no2-legends/takamiya-shinichi.html',
    detail:'グロービス・キャピタル・パートナーズ（GCP）代表パートナー。29歳でGCP参画、Forbes Midas List日本1位（2018）。' },
  { cat:'person', name:'松本 勇気',          lat:31.5966, lng:130.5571, place:'鹿児島, Japan',              source:'../no2-legends/matsumoto-yuki.html',
    detail:'LayerX代表取締役CTO。鹿児島の片田舎・プログラミング歴ゼロから東大→学生起業→Gunosy・DMM・LayerXで3社CTO歴任。' },
  { cat:'person', name:'黒田官兵衛',         lat:34.8154, lng:134.6850, place:'姫路, 兵庫, Japan',          source:'../no2-legends/kuroda-kanbei.html',
    detail:'豊臣秀吉の天下統一を支えた稀代の軍師。「百万石なら天下を取る」と恐れられ即座に剃髪・退いた引き際の名人。' },
  { cat:'person', name:'諸葛亮（孔明）',     lat:35.0395, lng:118.3265, place:'琅琊（現 山東省臨沂）, China', source:'../no2-legends/zhuge-liang.html',
    detail:'三顧の礼で迎えられた蜀漢の丞相。帝位譲渡を許可されながら固辞し五丈原で陣没。「鞠躬尽瘁」の体現。' },

  /* ============ 主要No.1（参考） ============ */
  { cat:'person', name:'Steve Jobs',         lat:37.7749, lng:-122.4194, place:'San Francisco, California, USA', source:'../no2-legends/tim-cook.html',
    detail:'Apple共同創業者（1955–2011）。Tim Cook・Jony Ive とのペアで取り上げられる「No.1」。' },
  { cat:'person', name:'Bill Gates',         lat:47.6062, lng:-122.3321, place:'Seattle, Washington, USA',        source:'../no2-legends/steve-ballmer.html',
    detail:'Microsoft共同創業者（1955–）。Steve Ballmerの旧友・寮の隣人。' },
  { cat:'person', name:'Warren Buffett',     lat:41.2565, lng:-95.9345,  place:'Omaha, Nebraska, USA',            source:'../no2-legends/charlie-munger.html',
    detail:'Berkshire Hathaway会長兼CEO。Charlie Mungerの相棒として64年。' },
  { cat:'person', name:'Sam Altman',         lat:38.6270, lng:-90.1994,  place:'St. Louis, Missouri, USA',        source:'../no2-legends/greg-brockman.html',
    detail:'OpenAI CEO。St. Louis出身、Stanford中退、Loopt創業→Y Combinator代表→OpenAI共同創業。' },
  { cat:'person', name:'Mark Zuckerberg',    lat:41.0340, lng:-73.7629,  place:'White Plains, New York, USA',     source:'../no2-legends/sheryl-sandberg.html',
    detail:'Meta（旧Facebook）創業者・CEO。Harvard中退。Sheryl SandbergをCOOに迎え事業化。' },
  { cat:'person', name:'山田 進太郎',         lat:35.6762, lng:139.6503,  place:'東京, Japan',                     source:'../no2-legends/fumiaki-koizumi.html',
    detail:'メルカリ創業者・CEO／会長。小泉文明をCOOに迎えた「No.1」。' },
  { cat:'person', name:'佐々木 大輔',         lat:35.6762, lng:139.6503,  place:'東京, Japan',                     source:'../no2-legends/togo-sumito.html',
    detail:'freee創業者・CEO／東後澄人をCOOに迎えた「No.1」。' },
  { cat:'person', name:'福島 良典',           lat:35.6762, lng:139.6503,  place:'東京, Japan',                     source:'../no2-legends/matsumoto-yuki.html',
    detail:'LayerX代表取締役CEO／Gunosy創業者。松本勇気をCTOに迎えた「No.1」。' },
  { cat:'person', name:'豊臣 秀吉',           lat:35.0863, lng:136.9181,  place:'尾張 中村（現 名古屋）, Japan',   source:'../no2-legends/kuroda-kanbei.html',
    detail:'戦国の天下人。黒田官兵衛・竹中半兵衛を「両兵衛」として登用。' },
  { cat:'person', name:'劉備 玄徳',           lat:32.5503, lng:114.0666,  place:'涿県（現 河北省涿州）, China',    source:'../no2-legends/zhuge-liang.html',
    detail:'三国時代 蜀漢初代皇帝。三顧の礼で諸葛亮を迎える。' },

  /* ============ 各国 政治家・偉人 ============ */
  { cat:'person', name:'徳川 家康',           lat:34.9667, lng:137.1554,  place:'三河 岡崎, Japan',                 source:'../geo-history/japan.html',
    detail:'江戸幕府初代将軍／265年の平和の礎。岡崎城で生まれる。' },
  { cat:'person', name:'織田 信長',           lat:35.0667, lng:136.9667,  place:'尾張 那古野（現 名古屋）, Japan',  source:'../geo-history/japan.html',
    detail:'戦国の革新者。鉄砲・楽市楽座／1582年本能寺で横死。' },
  { cat:'person', name:'伊藤 博文',           lat:34.4081, lng:131.4014,  place:'山口 萩, Japan',                   source:'../geo-history/japan.html',
    detail:'初代内閣総理大臣／大日本帝国憲法制定の中心。萩の貧農の家に生まれる。' },
  { cat:'person', name:'吉田 茂',             lat:35.3107, lng:139.3220,  place:'神奈川 大磯, Japan',               source:'../geo-history/japan.html',
    detail:'戦後5度首相／日米安保・サンフランシスコ平和条約／戦後復興の礎。晩年は大磯で過ごす。' },
  { cat:'person', name:'田中 角栄',           lat:37.3686, lng:138.5567,  place:'新潟 柏崎（旧西山町）, Japan',     source:'../geo-history/japan.html',
    detail:'日本列島改造論／日中国交正常化／ロッキード事件で失脚。新潟県の貧農出身。' },
  { cat:'person', name:'安倍 晋三',           lat:33.9580, lng:130.9408,  place:'山口 下関, Japan',                 source:'../geo-history/japan.html',
    detail:'戦後最長の在任日数（通算 3,188 日）。山口県（地盤）で2022年銃撃。' },
  { cat:'person', name:'小泉 純一郎',         lat:35.2815, lng:139.6717,  place:'神奈川 横須賀, Japan',             source:'../geo-history/japan.html',
    detail:'郵政民営化／構造改革／「自民党をぶっ壊す」の長期政権。' },
  { cat:'person', name:'福澤 諭吉',           lat:33.5996, lng:131.1880,  place:'大分 中津, Japan',                 source:'../geo-history/japan.html',
    detail:'慶應義塾創設／『学問のすゝめ』／旧1万円札。中津藩士の子として大阪で生まれ中津で育つ。' },
  { cat:'person', name:'松下 幸之助',         lat:34.2305, lng:135.1708,  place:'和歌山, Japan',                    source:'../geo-history/japan.html',
    detail:'パナソニック創業者／「経営の神様」。和歌山の貧農出身、9歳で大阪へ丁稚奉公。' },
  { cat:'person', name:'本田 宗一郎',         lat:34.7108, lng:137.7261,  place:'静岡 浜松, Japan',                 source:'../geo-history/japan.html',
    detail:'本田技研工業創業者／町工場から世界のHondaへ。浜松の鍛冶屋の子。' },
  { cat:'person', name:'盛田 昭夫',           lat:35.1815, lng:136.9066,  place:'愛知 名古屋, Japan',               source:'../geo-history/japan.html',
    detail:'ソニー共同創業／ウォークマンで世界制覇。常滑の酒造家の長男。' },
  { cat:'person', name:'稲盛 和夫',           lat:31.5966, lng:130.5571,  place:'鹿児島, Japan',                    source:'../geo-history/japan.html',
    detail:'京セラ・KDDI創業／JAL再建／盛和塾／「人間として何が正しいか」。鹿児島薬師町出身。' },
  { cat:'person', name:'宮崎 駿',             lat:35.7226, lng:139.7444,  place:'東京 文京区, Japan',               source:'../geo-history/japan.html',
    detail:'スタジオジブリ／2003年・2024年アカデミー賞2回受賞。文京区生まれ。' },
  { cat:'person', name:'村上 春樹',           lat:35.0116, lng:135.7681,  place:'京都 伏見, Japan',                 source:'../geo-history/japan.html',
    detail:'『ノルウェイの森』『1Q84』『海辺のカフカ』／毎年ノーベル文学賞候補。京都伏見生まれ・神戸育ち。' },
  { cat:'person', name:'大谷 翔平',           lat:39.1547, lng:141.1377,  place:'岩手 奥州, Japan',                 source:'../geo-history/japan.html',
    detail:'MLB ロサンゼルス・ドジャース／2024年に MLB 初の50-50（HR・盗塁）達成。岩手県奥州市水沢出身。' },
  { cat:'person', name:'湯川 秀樹',           lat:35.0116, lng:135.7681,  place:'京都, Japan',                      source:'../geo-history/japan.html',
    detail:'日本人初のノーベル賞（物理学・1949）／中間子論。東京生まれ・京都帝大で活動。' },
  { cat:'person', name:'黒澤 明',             lat:35.5614, lng:139.7160,  place:'東京 大田区, Japan',               source:'../geo-history/japan.html',
    detail:'『七人の侍』『羅生門』『生きる』／世界のKurosawa。大田区生まれ。' },

  /* ===== Korea ===== */
  { cat:'person', name:'世宗大王（Sejong）',  lat:37.5665, lng:126.9780,  place:'漢陽（現 ソウル）, Korea',         source:'../geo-history/korea.html',
    detail:'朝鮮第4代王／<strong>ハングル制定</strong>（1443）／韓国紙幣1万ウォン札の肖像。' },
  { cat:'person', name:'朴 正煕',             lat:36.1190, lng:128.3445,  place:'慶尚北道 亀尾, Korea',             source:'../geo-history/korea.html',
    detail:'「漢江の奇跡」を主導／18年独裁／側近に暗殺。亀尾の貧農出身。' },
  { cat:'person', name:'金 大中',             lat:34.7842, lng:126.3955,  place:'全羅南道 木浦（新安郡）, Korea',  source:'../geo-history/korea.html',
    detail:'「太陽政策」／2000年初の南北首脳会談／ノーベル平和賞（2000）。' },
  { cat:'person', name:'李 秉喆（Lee Byung-chul）', lat:36.3526, lng:128.6970, place:'慶尚北道 義城, Korea',     source:'../geo-history/korea.html',
    detail:'サムスン創業者／韓国財閥史の父（1910–1987）。義城の地主の家に生まれる。' },
  { cat:'person', name:'鄭 周永（Chung Ju-yung）',  lat:38.5,   lng:127.9,    place:'江原道 通川（現 北朝鮮）, Korea',  source:'../geo-history/korea.html',
    detail:'現代グループ創業者／自動車・造船・建設の御三家を一代で築く（1915–2001）。' },
  { cat:'person', name:'李 在明',             lat:36.5684, lng:128.7294,  place:'慶尚北道 安東, Korea',             source:'../geo-history/korea.html',
    detail:'共に民主党／2025年6月就任。貧困家庭出身、独学で司法試験合格。' },
  { cat:'person', name:'尹 錫悦',             lat:37.5665, lng:126.9780,  place:'ソウル, Korea',                    source:'../geo-history/korea.html',
    detail:'検察総長出身／2024年12月戒厳令で弾劾→2025年4月罷免。' },
  { cat:'person', name:'奉 俊昊（Bong Joon-ho）',   lat:35.8714, lng:128.6014, place:'大邱, Korea',                 source:'../geo-history/korea.html',
    detail:'『パラサイト』（2019）／非英語映画初のアカデミー作品賞。大邱生まれ。' },

  /* ===== Taiwan ===== */
  { cat:'person', name:'李 登輝（Lee Teng-hui）',  lat:25.2540, lng:121.5044, place:'新北 三芝, Taiwan',           source:'../geo-history/taiwan.html',
    detail:'「台湾民主化の父」／本省人初の総統（1988–2000）／日本統治期に京都帝大／親日。' },
  { cat:'person', name:'蔡 英文（Tsai Ing-wen）',  lat:25.0330, lng:121.5654, place:'台北, Taiwan',                source:'../geo-history/taiwan.html',
    detail:'初の女性総統（2016–2024）／同性婚アジア初合法化／半導体外交。' },
  { cat:'person', name:'張 忠謀（Morris Chang）',  lat:29.8683, lng:121.5440, place:'寧波, China（中国本土生まれ）→Taiwan', source:'../geo-history/taiwan.html',
    detail:'TSMC創業者（1987）／世界半導体産業を「設計」と「製造」に分離した張本人。寧波生まれ・米国MIT博士。' },
  { cat:'person', name:'李 安（Ang Lee）',     lat:22.6716, lng:120.4881, place:'屏東, Taiwan',                    source:'../geo-history/taiwan.html',
    detail:'『臥虎藏龍』『ブロークバック・マウンテン』『LIFE』／米アカデミー監督賞2回。屏東出身。' },
  { cat:'person', name:'唐 鳳（Audrey Tang）',     lat:25.0330, lng:121.5654, place:'台北, Taiwan',                source:'../geo-history/taiwan.html',
    detail:'世界初のデジタル担当大臣（2016–2024）／オープンガバメントの旗手。' },

  /* ===== China ===== */
  { cat:'person', name:'孔子',                 lat:35.5810, lng:116.9881, place:'魯国 曲阜（山東省）, China',      source:'../geo-history/china.html',
    detail:'儒教の祖（BC 551–479）／東アジア倫理の基盤。曲阜は孔子廟のある聖地。' },
  { cat:'person', name:'毛 沢東',               lat:27.9221, lng:112.5294, place:'湖南 韶山, China',              source:'../geo-history/china.html',
    detail:'中華人民共和国建国（1949）／文化大革命で多大な犠牲。韶山の貧農の子。' },
  { cat:'person', name:'鄧 小平',               lat:30.4727, lng:106.6328, place:'四川 広安, China',              source:'../geo-history/china.html',
    detail:'改革開放の設計者／「先富論」／天安門事件の決断者（1904–1997）。' },
  { cat:'person', name:'習 近平',               lat:39.9042, lng:116.4074, place:'北京, China',                   source:'../geo-history/china.html',
    detail:'中共総書記（2012〜）／反腐敗・「中国の夢」／2018年憲法改正で続投可能に。北京生まれ・陝西省下放経験。' },
  { cat:'person', name:'孫 文（Sun Yat-sen）',  lat:22.4530, lng:113.5256, place:'広東 香山 翠亨村（現 中山市）, China', source:'../geo-history/china.html',
    detail:'辛亥革命／中華民国建国／「国父」（中台双方から尊敬）。広東省 香山県の村出身。' },
  { cat:'person', name:'Jack Ma（馬雲）',       lat:30.2741, lng:120.1551, place:'浙江 杭州, China',              source:'../geo-history/china.html',
    detail:'Alibaba創業者（1964–）／2020年以降公の場から消える。杭州生まれ・英語教師から起業。' },
  { cat:'person', name:'Pony Ma（馬化騰）',     lat:23.3540, lng:116.6822, place:'広東 汕頭, China',              source:'../geo-history/china.html',
    detail:'Tencent創業者（1971–）／世界最大のゲーム会社。' },
  { cat:'person', name:'任 正非（Ren Zhengfei）', lat:26.0561, lng:105.7686, place:'貴州 鎮寧, China',             source:'../geo-history/china.html',
    detail:'Huawei創業者（1944–）／米中対立の象徴的存在。' },

  /* ===== Russia ===== */
  { cat:'person', name:'ピョートル大帝',       lat:55.7558, lng:37.6173,   place:'モスクワ, Russia',               source:'../geo-history/russia.html',
    detail:'西欧化改革／サンクトペテルブルク建設（1703）／海軍創設（1672–1725）。' },
  { cat:'person', name:'レーニン',              lat:54.3187, lng:48.3978,   place:'シンビルスク（現 ウリヤノフスク）, Russia', source:'../geo-history/russia.html',
    detail:'ロシア革命指導者／ソ連建国の父（1870–1924）。レーニン廟は現在もモスクワ赤の広場。' },
  { cat:'person', name:'スターリン',            lat:41.9847, lng:44.1115,   place:'ゴリ, Georgia',                  source:'../geo-history/russia.html',
    detail:'ソ連最高指導者（1879–1953）／大粛清（数百万人死亡）／工業化／第二次大戦勝利。ジョージア生まれ。' },
  { cat:'person', name:'プーチン',              lat:59.9311, lng:30.3609,   place:'サンクトペテルブルク（旧レニングラード）, Russia', source:'../geo-history/russia.html',
    detail:'1999年〜の最高指導者／KGB出身／2024年5期目当選・任期2030年まで。' },
  { cat:'person', name:'ゴルバチョフ',          lat:44.2118, lng:42.0578,   place:'スタヴロポリ地方, Russia',       source:'../geo-history/russia.html',
    detail:'ペレストロイカ・グラスノスチ／ノーベル平和賞（1990）／意図せずソ連解体（1931–2022）。' },
  { cat:'person', name:'トルストイ',            lat:54.0744, lng:37.5240,   place:'ヤースナヤ・ポリャーナ（トゥーラ州）, Russia', source:'../geo-history/russia.html',
    detail:'『戦争と平和』『アンナ・カレーニナ』（1828–1910）。生家・墓所のヤースナヤ・ポリャーナ。' },
  { cat:'person', name:'ドストエフスキー',      lat:55.7558, lng:37.6173,   place:'モスクワ, Russia',               source:'../geo-history/russia.html',
    detail:'『罪と罰』『カラマーゾフの兄弟』（1821–1881）。モスクワで生まれ・サンクトペテルブルクで活動。' },
  { cat:'person', name:'チャイコフスキー',      lat:57.0517, lng:53.9844,   place:'ヴォトキンスク, Russia',         source:'../geo-history/russia.html',
    detail:'『白鳥の湖』『くるみ割り人形』（1840–1893）。' },
  { cat:'person', name:'ガガーリン',            lat:55.5860, lng:34.5811,   place:'クルシノ村（スモレンスク州）, Russia', source:'../geo-history/russia.html',
    detail:'世界初の有人宇宙飛行（1961.4.12）（1934–1968）。' },

  /* ===== USA ===== */
  { cat:'person', name:'George Washington',    lat:38.0975, lng:-76.6841,  place:'Westmoreland County, Virginia, USA', source:'../geo-history/usa.html',
    detail:'建国の父／初代大統領／「2期で退く」伝統を確立（1732–1799）。' },
  { cat:'person', name:'Abraham Lincoln',      lat:37.5734, lng:-85.7308,  place:'Hodgenville, Kentucky, USA',          source:'../geo-history/usa.html',
    detail:'第16代／南北戦争を戦い奴隷解放宣言／合衆国の維持（1809–1865）。' },
  { cat:'person', name:'Barack Obama',         lat:21.3099, lng:-157.8581, place:'Honolulu, Hawaii, USA',               source:'../geo-history/usa.html',
    detail:'第44代／初の黒人大統領／ACA（オバマケア）／ノーベル平和賞。Honolulu生まれ。' },
  { cat:'person', name:'Donald Trump',         lat:40.7282, lng:-73.7949,  place:'Queens, New York, USA',               source:'../geo-history/usa.html',
    detail:'第45・47代／非連続2期目（132年ぶり）／米中対立・移民政策厳格化。Queens生まれ。' },
  { cat:'person', name:'JFK',                  lat:42.3318, lng:-71.1212,  place:'Brookline, Massachusetts, USA',       source:'../geo-history/usa.html',
    detail:'第35代／キューバ危機／公民権法案／1963年暗殺（1917–1963）。' },
  { cat:'person', name:'Elon Musk',            lat:-25.7479, lng:28.2293,  place:'Pretoria, South Africa',              source:'../geo-history/usa.html',
    detail:'Tesla・SpaceX・X／Trump政権で政府効率化省（DOGE）。プレトリア生まれ・カナダ→米国。' },
  { cat:'person', name:'Jeff Bezos',           lat:35.0844, lng:-106.6504, place:'Albuquerque, New Mexico, USA',        source:'../geo-history/usa.html',
    detail:'Amazon創業／Blue Origin・Washington Post所有者。' },
  { cat:'person', name:'MLK Jr.',              lat:33.7490, lng:-84.3880,  place:'Atlanta, Georgia, USA',               source:'../geo-history/usa.html',
    detail:'公民権運動／非暴力抵抗／ノーベル平和賞（1964）（1929–1968）。' },

  /* ============ 企業 本社 ============ */
  /* USA */
  { cat:'company', name:'Apple Inc.',          lat:37.3349, lng:-122.0090, place:'Cupertino, California, USA',          source:'../no2-legends/tim-cook.html',
    detail:'Apple Park本社／時価総額 世界トップ級。Tim Cook CEO。' },
  { cat:'company', name:'Google / Alphabet',   lat:37.4220, lng:-122.0841, place:'Mountain View, California, USA',      source:'../no2-legends/sundar-pichai.html',
    detail:'Googleplex／検索・広告・YouTube・Android・Gemini。Sundar Pichai CEO。' },
  { cat:'company', name:'Microsoft',           lat:47.6396, lng:-122.1283, place:'Redmond, Washington, USA',            source:'../no2-legends/steve-ballmer.html',
    detail:'OS・Azure・OpenAI 出資。Satya Nadella CEO。元CEO Steve Ballmer の長年の地盤。' },
  { cat:'company', name:'Meta',                lat:37.4845, lng:-122.1483, place:'Menlo Park, California, USA',         source:'../no2-legends/sheryl-sandberg.html',
    detail:'Facebook・Instagram・WhatsApp・Threads・Quest。Zuckerberg CEO／元COO Sheryl Sandberg。' },
  { cat:'company', name:'OpenAI',              lat:37.7820, lng:-122.3960, place:'San Francisco, California, USA',      source:'../no2-legends/greg-brockman.html',
    detail:'ChatGPT・GPT-5。Sam Altman CEO／Greg Brockman President／元CTO Mira Murati。' },
  { cat:'company', name:'Stripe',              lat:37.7765, lng:-122.4174, place:'San Francisco, California, USA',      source:'../no2-legends/john-collison.html',
    detail:'決済プラットフォーム。Patrick Collison CEO／John Collison President。Dublin にも本社機能。' },
  { cat:'company', name:'Tesla',               lat:30.2240, lng:-97.6190,  place:'Austin, Texas, USA',                  source:'../geo-history/usa.html',
    detail:'Gigafactory Texas／2021年にPalo AltoからAustinへ本社移転。Elon Musk CEO。' },
  { cat:'company', name:'NVIDIA',              lat:37.3699, lng:-121.9637, place:'Santa Clara, California, USA',        source:'../geo-history/usa.html',
    detail:'GPU・AIで世界 1〜2 位の時価総額（約 3.5 兆ドル）。Jensen Huang CEO。' },
  { cat:'company', name:'Amazon',              lat:47.6228, lng:-122.3365, place:'Seattle, Washington, USA',            source:'../geo-history/usa.html',
    detail:'EC・AWS／世界最大のクラウド。' },
  { cat:'company', name:'Berkshire Hathaway',  lat:41.2616, lng:-95.9376,  place:'Omaha, Nebraska, USA',                source:'../no2-legends/charlie-munger.html',
    detail:'Buffett・Munger コンビが64年間運営した投資持株。' },

  /* Japan */
  { cat:'company', name:'Toyota Motor',        lat:35.0823, lng:137.1565,  place:'愛知 豊田市, Japan',                  source:'../geo-history/japan.html',
    detail:'世界販売台数 5 年連続 1 位／時価総額は日本最大。' },
  { cat:'company', name:'Sony Group',          lat:35.6308, lng:139.7404,  place:'東京 港区 港南, Japan',               source:'../geo-history/japan.html',
    detail:'家電・半導体イメージセンサ世界1位・エンタメ・金融。' },
  { cat:'company', name:'SoftBank Group',      lat:35.6627, lng:139.7616,  place:'東京 港区 汐留, Japan',               source:'../geo-history/japan.html',
    detail:'孫正義／Arm・Vision Fund／時価総額 17 兆円超。' },
  { cat:'company', name:'Nintendo',            lat:34.9706, lng:135.7560,  place:'京都 南区 上鳥羽, Japan',             source:'../geo-history/japan.html',
    detail:'ゲーム・IP／時価総額 11 兆円超（2025）。' },
  { cat:'company', name:'メルカリ',             lat:35.6714, lng:139.7088,  place:'東京 港区 六本木, Japan',             source:'../no2-legends/fumiaki-koizumi.html',
    detail:'C2Cマーケットプレイス／2018年マザーズ上場。山田進太郎CEO・小泉文明 元会長。' },
  { cat:'company', name:'LayerX',              lat:35.6833, lng:139.7714,  place:'東京 中央区 日本橋, Japan',           source:'../no2-legends/matsumoto-yuki.html',
    detail:'Bakuraku（バクラク）・SaaS／福島良典CEO・松本勇気CTO（共同代表）。' },

  /* Taiwan */
  { cat:'company', name:'TSMC',                lat:24.7741, lng:121.0184,  place:'新竹 科学園区, Taiwan',               source:'../geo-history/taiwan.html',
    detail:'世界先端ロジック半導体の約90%を握る／時価総額 約 8,000億ドル。Morris Chang創業（1987）。' },
  { cat:'company', name:'Foxconn（鴻海）',      lat:25.0792, lng:121.3884,  place:'新北 林口（土城）, Taiwan',           source:'../geo-history/taiwan.html',
    detail:'世界最大級EMS／iPhone組立で有名。Terry Gou（郭台銘）創業。' },
  { cat:'company', name:'国泰金控',             lat:25.0330, lng:121.5654,  place:'台北 信義, Taiwan',                   source:'../geo-history/taipei.html',
    detail:'台湾最大級の金融持株／生保・銀行・証券・損保。' },

  /* Korea */
  { cat:'company', name:'Samsung Electronics', lat:37.2562, lng:127.0529,  place:'京畿道 水原, Korea',                  source:'../geo-history/korea.html',
    detail:'本社は水原・スウォン／ソウル瑞草の Samsung Town に経営機能。半導体・スマホ・家電・バイオ。' },
  { cat:'company', name:'Hyundai Motor Group', lat:37.4730, lng:127.0394,  place:'ソウル 瑞草 梁才, Korea',             source:'../geo-history/korea.html',
    detail:'世界販売台数 3 位／旧 韓電本社跡地に GBC（最高層 569m）建設中。' },
  { cat:'company', name:'SK Group',            lat:37.5704, lng:126.9783,  place:'ソウル 鍾路, Korea',                  source:'../geo-history/korea.html',
    detail:'2位財閥／SK Hynix・SK Telecom の親会社。' },
  { cat:'company', name:'LG Group',            lat:37.5249, lng:126.9276,  place:'ソウル 永登浦 汝矣島, Korea',         source:'../geo-history/korea.html',
    detail:'家電・化学・バッテリー・ディスプレイ／LGツインタワー。' },
  { cat:'company', name:'HYBE',                lat:37.5326, lng:127.0046,  place:'ソウル 龍山 漢南洞, Korea',           source:'../geo-history/seoul.html',
    detail:'BTS・SEVENTEEN・LE SSERAFIM／時価総額 韓国エンタメ1位。方時赫 創業。' },
  { cat:'company', name:'Coupang',             lat:37.5058, lng:127.1057,  place:'ソウル 松坡 蚕室, Korea',             source:'../geo-history/seoul.html',
    detail:'EC・物流／韓国の Amazon／NYSE 上場／ロケット配送（翌朝着）。' },

  /* China */
  { cat:'company', name:'Tencent（騰訊）',      lat:22.5395, lng:113.9536,  place:'広東 深圳 南山, China',               source:'../geo-history/china.html',
    detail:'WeChat（微信）／時価総額 約4,500億ドル／世界最大のゲーム会社。' },
  { cat:'company', name:'Alibaba Group',       lat:30.1843, lng:120.0292,  place:'浙江 杭州 余杭, China',               source:'../geo-history/china.html',
    detail:'淘宝（Taobao）・天猫（Tmall）・Alipay・AlibabaCloud。Jack Ma 創業。' },
  { cat:'company', name:'BYD',                 lat:22.6142, lng:114.0500,  place:'広東 深圳 坪山, China',               source:'../geo-history/china.html',
    detail:'2024年世界 EV 販売台数で Tesla を抜き世界1位／Buffett 投資。' },
  { cat:'company', name:'Huawei',              lat:22.6435, lng:113.9180,  place:'広東 深圳 龍崗, China',               source:'../geo-history/china.html',
    detail:'米制裁下でも独自半導体（Kirin・Ascend）で復活／非上場。任正非 創業。' },
  { cat:'company', name:'ByteDance',           lat:39.9968, lng:116.3047,  place:'北京 海淀, China',                    source:'../geo-history/china.html',
    detail:'TikTok・抖音／非上場ながら世界最高評価額のユニコーン（約4,000億ドル）。' },

  /* Russia */
  { cat:'company', name:'Gazprom',             lat:59.9343, lng:30.3351,   place:'サンクトペテルブルク, Russia',         source:'../geo-history/russia.html',
    detail:'世界最大級の天然ガス企業／元国営／パイプライン Nord Stream・Power of Siberia。' },
  { cat:'company', name:'Sberbank',            lat:55.7416, lng:37.6147,   place:'モスクワ, Russia',                    source:'../geo-history/russia.html',
    detail:'ロシア最大の銀行／個人口座シェア約50%／IT投資で先進的。' },

  /* ============ 特産品・名物 ============ */
  /* Taipei area */
  { cat:'product', name:'鉄観音茶',             lat:24.9641, lng:121.5887,  place:'台北 文山 猫空, Taiwan',              source:'../geo-history/taipei.html',
    detail:'樹齢100年級の老茶樹／焙煎香が強い／猫空ロープウェイ。' },
  { cat:'product', name:'文山包種茶',           lat:24.9343, lng:121.7128,  place:'新北 坪林（南港隣接）, Taiwan',       source:'../geo-history/taipei.html',
    detail:'日本統治期に開発された半発酵青茶／淡い花香。' },
  { cat:'product', name:'パイナップルケーキ',   lat:25.0517, lng:121.5778,  place:'台北 松山（佳徳糕餅本店）, Taiwan',   source:'../geo-history/taipei.html',
    detail:'佳徳・微熱山丘・李製餅家／台北土産の定番。' },
  { cat:'product', name:'小籠包（鼎泰豐）',     lat:25.0331, lng:121.5301,  place:'台北 大安 信義路本店, Taiwan',        source:'../geo-history/taipei.html',
    detail:'世界基準を作った台湾発の小籠包名店。' },
  { cat:'product', name:'タピオカミルクティー（春水堂）', lat:24.1602, lng:120.6857, place:'台中 西区, Taiwan（発祥）',  source:'../geo-history/taiwan.html',
    detail:'1983年に台中の春水堂で発明／台北で世界に広がる。' },

  /* Busan / Korea */
  { cat:'product', name:'釜山オムク（魚すり身）', lat:35.1011, lng:129.0349, place:'釜山, Korea',                       source:'../geo-history/busan.html',
    detail:'三進・古来思・サムジン／日本統治期の蒲鉾文化が独自進化。' },
  { cat:'product', name:'ミルミョン（小麦冷麺）', lat:35.1577, lng:129.0599, place:'釜山 西面, Korea',                  source:'../geo-history/busan.html',
    detail:'朝鮮戦争中、北からの避難民が蕎麦粉が手に入らず小麦で作ったのが起源。' },
  { cat:'product', name:'씨앗ホットック',        lat:35.0989, lng:129.0307,  place:'釜山 中区 BIFF広場, Korea',          source:'../geo-history/busan.html',
    detail:'釜山発祥の進化系ホットック／南浦洞 BIFF 広場の屋台が有名。' },
  { cat:'product', name:'機張カニ',              lat:35.2440, lng:129.2156,  place:'釜山 機張郡, Korea',                 source:'../geo-history/busan.html',
    detail:'秋〜冬／市場で活カニを購入できる／海雲台からドライブ30分。' },

  /* Tokyo */
  { cat:'product', name:'江戸切子',              lat:35.7090, lng:139.8146,  place:'東京 江東・墨田, Japan',             source:'../geo-history/tokyo.html',
    detail:'伝統工芸／カットガラス／高級ギフト。' },
  { cat:'product', name:'江戸前寿司',            lat:35.6660, lng:139.7704,  place:'東京 中央 銀座, Japan',              source:'../geo-history/tokyo.html',
    detail:'江戸湾の魚＋酢飯／世界の寿司の起源／豊洲市場が現代の中心。' },
  { cat:'product', name:'もんじゃ焼き',          lat:35.6622, lng:139.7836,  place:'東京 中央 月島, Japan',              source:'../geo-history/tokyo.html',
    detail:'月島が発祥地／お好み焼きより液状で「焼きながら食べる」。' },

  /* China */
  { cat:'product', name:'北京ダック',            lat:39.9087, lng:116.4118,  place:'北京 王府井（全聚徳）, China',        source:'../geo-history/china.html',
    detail:'清代から続く宮廷料理／全聚徳が老舗の代表。' },
  { cat:'product', name:'麻婆豆腐',              lat:30.6598, lng:104.0633,  place:'四川 成都, China',                   source:'../geo-history/china.html',
    detail:'清末の成都・陳麻婆豆腐が発祥／激辛・痺れの代名詞。' },

  /* ============ 都市・名所 ============ */
  { cat:'city', name:'故宮博物院',              lat:25.1024, lng:121.5485,  place:'台北 士林, Taiwan',                  source:'../geo-history/taipei.html',
    detail:'北京から運ばれた中華王朝5,000年の至宝70万点／翠玉白菜・肉形石。' },
  { cat:'city', name:'台北101',                 lat:25.0339, lng:121.5645,  place:'台北 信義, Taiwan',                  source:'../geo-history/taipei.html',
    detail:'2004〜2010年世界最高層／89F展望台／365台/秒のエレベーター。' },
  { cat:'city', name:'海雲台ビーチ',            lat:35.1587, lng:129.1604,  place:'釜山 海雲台, Korea',                 source:'../geo-history/busan.html',
    detail:'韓国最大級ビーチ（1.5km）／映画祭BIFFの主要会場。' },
  { cat:'city', name:'甘川文化村',              lat:35.0975, lng:129.0103,  place:'釜山 沙下, Korea',                   source:'../geo-history/busan.html',
    detail:'コリアのサントリーニ／カラフルな山肌の階段集落／2009年都市再生プロジェクト。' },
  { cat:'city', name:'景福宮',                  lat:37.5796, lng:126.9770,  place:'ソウル 鍾路, Korea',                 source:'../geo-history/seoul.html',
    detail:'朝鮮王朝の正宮（1395創建）／光化門・勤政殿／守門将交代式。' },
  { cat:'city', name:'東京スカイツリー',        lat:35.7101, lng:139.8107,  place:'東京 墨田, Japan',                   source:'../geo-history/tokyo.html',
    detail:'634m／世界第3位の高さ／2012年開業。' },
  { cat:'city', name:'富士山',                  lat:35.3606, lng:138.7274,  place:'静岡・山梨, Japan',                  source:'../geo-history/japan.html',
    detail:'3,776m／世界文化遺産（2013）／登山シーズン7〜9月。' },
  { cat:'city', name:'万里の長城（八達嶺）',    lat:40.3587, lng:116.0167,  place:'北京 北部, China',                   source:'../geo-history/china.html',
    detail:'世界遺産／総延長 21,000km／八達嶺・慕田峪が観光定番。' },
  { cat:'city', name:'兵馬俑',                  lat:34.3848, lng:109.2786,  place:'陝西 西安, China',                   source:'../geo-history/china.html',
    detail:'世界遺産／秦始皇帝陵／8,000体の等身大兵士像。' },
  { cat:'city', name:'赤の広場・クレムリン',    lat:55.7539, lng:37.6208,   place:'モスクワ, Russia',                    source:'../geo-history/russia.html',
    detail:'世界遺産／聖ワシリー大聖堂／レーニン廟／グム百貨店。' },
  { cat:'city', name:'エルミタージュ美術館',    lat:59.9398, lng:30.3146,   place:'サンクトペテルブルク, Russia',         source:'../geo-history/russia.html',
    detail:'世界四大美術館の一つ／エカテリーナ2世が冬宮殿に収集を始めた。' },
  { cat:'city', name:'グランド・キャニオン',    lat:36.0544, lng:-112.1401,  place:'Arizona, USA',                       source:'../geo-history/usa.html',
    detail:'世界遺産／長さ446km／コロラド川による浸食。' },
  { cat:'city', name:'自由の女神',              lat:40.6892, lng:-74.0445,  place:'New York, USA',                      source:'../geo-history/usa.html',
    detail:'1886年フランスから贈呈／米独立100周年記念／世界遺産。' },

  /* ============ 歴史的場所 ============ */
  { cat:'history', name:'Goree島（奴隷貿易遺跡）', lat:14.6669, lng:-17.3989, place:'Dakar, Senegal',                  source:'../geo-history/',
    detail:'世界遺産／大西洋奴隷貿易の象徴／「奴隷の家」博物館／Clinton・Obama・Pope来訪。' },
  { cat:'history', name:'広島平和記念公園',     lat:34.3955, lng:132.4536,   place:'広島, Japan',                        source:'../geo-history/japan.html',
    detail:'1945.8.6 原爆投下地／原爆ドーム（世界遺産）／平和記念資料館。' },
  { cat:'history', name:'真珠湾',               lat:21.3650, lng:-157.9507,  place:'Honolulu, Hawaii, USA',              source:'../geo-history/usa.html',
    detail:'1941.12.7 真珠湾攻撃／USS Arizona Memorial。' },
  { cat:'history', name:'板門店（DMZ）',        lat:37.9610, lng:126.6674,   place:'京畿道, Korea',                      source:'../geo-history/korea.html',
    detail:'1953年 朝鮮戦争休戦協定／世界で最も警備された境界線／南北首脳会談（2018）。' },
  { cat:'history', name:'天安門広場',           lat:39.9054, lng:116.3975,   place:'北京, China',                        source:'../geo-history/china.html',
    detail:'1949.10.1 中華人民共和国成立／1989.6.4 天安門事件／世界最大の広場。' },
  { cat:'history', name:'関ヶ原古戦場',         lat:35.3735, lng:136.4636,   place:'岐阜 関ヶ原, Japan',                 source:'../geo-history/japan.html',
    detail:'1600.10.21 天下分け目の合戦／徳川家康が勝利し江戸幕府成立への道筋。' },

];
